### ISSUE TITLE
Add policycoreutils-python as a dependency

### ISSUE THREAD

**Issue by Brueggus** [amuehlem/MISP-RPM#10]
Installing the misp-RPM (misp.spec) on a minimal install of CentOS or RHEL 7 yields lots of error messages like
`/var/tmp/rpm-tmp.wdKnZ4: Zeile 10: semanage: Kommando nicht gefunden.`

I'd suggest adding `policycoreutils-python` as a dependency to misp.spec as it contains `semanage`

**Comment by amuehlem** [comment]
Thank your for the hint, I've added it as a dependency to misp and built a new package (2.4.90-2)
