### ISSUE TITLE
Current RPM is defunct (due to upstream bug)

### ISSUE THREAD

**Issue by SteveClement** [amuehlem/MISP-RPM#13]
There was a bug with the version currently being installed in the RPM.

The database updates are being triggered in the wrong way, thus you will end up with an incomplete db.

Could you bump to a more recent version, please.

**Comment by amuehlem** [comment]
updated to use commit 231550075118dd394ecab67a0eb4885827676950

**Comment by SteveClement** [comment]
Testing :)
Thanks a lot.
