### ISSUE TITLE
An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by firebitsbr** [amuehlem/MISP-RPM#16]
I installed a minimal centos7-x86-64 and followed the instructions as per the link:
https://github.com/amuehlem/MISP-RPM/blob/master/INSTALL.md

But it did not work successfully and presented an error:
"An Internal Error Has Occurred."

**Comment by amuehlem** [comment]
Hi Mauro
Which version of the RPM did you install? There was an error in the DB handling in one of the last versions, 2.4.106-3 fixed it.

**Comment by amuehlem** [comment]
I just tested a fresh installation with 2.4.107-1, it worked.

**Comment by thetechhouse** [comment]
I get the same issue with 2.4.107-1 on CentOS 7.6.1810

**Comment by thetechhouse** [comment]
> Could not locate the GnuPG public key

Fixed the key issue (https://github.com/MISP/MISP/issues/1145) still getting 'An Internal Error has occurred'

**Comment by amuehlem** [comment]
What does the logfiles in MISP/apps/tmp/logs say?

**Comment by bhuvan2099** [comment]
Hi Amuehlem,

I'm facing the same issue, attaching error.log from /var/www/MISP/app/tmp/logs. I'm using Ubuntu 16 for MISP instance.

[error.log](https://github.com/amuehlem/MISP-RPM/files/3265861/error.log)

**Comment by amuehlem** [comment]
Your install RPMs on Ubuntu? This does not make sense if you ask me. The RPMs are created to be installed in CentOS or Red Hat Linux. The documentation to install MISP on Ubuntu is very good and you can just follow the steps. So far I don't know if anyone is creating packages for debian or ubuntu.

By looking into your error.log, it seems the configuration is not done properly

"Database connection "Mysql" is missing, or could not be created"
Please check the database settings in MISP/app/Config/database.php

"Fatal Error (1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 35191008 bytes) in [/var/www/MISP/app/Controller/EventsController.php, line 2846]"

States you should adjust the 'memory_limit' in php.ini

**Comment by bhuvan2099** [comment]
Hi Amuehlem,

I didn't install any RPM's on my server not sure how they are popping up. I installed my MISP instance using the AutoMISP script from here https://github.com/da667/AutoMISP

Below is my database.php, it seems legit. Pls suggest what i'm doing wrong here?

class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		//'datasource' => 'Database/Postgres',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'misp',
		'port' => 3306, // MySQL & MariaDB
		//'port' => 5432, // PostgreSQL
		'password' => 'ayylmaoayylmaoayylmaoayylmao',
		'database' => 'misp',
		'prefix' => '',
		'encoding' => 'utf8',
	);
}

**Comment by amuehlem** [comment]
If it's not related to the RPMs than you should ask in the project where you have the AutoMISP script from or on the MISP Support Channel on Gitter.
