### ISSUE TITLE
Patch missing in SOURCES dir

### ISSUE THREAD

**Issue by Brueggus** [amuehlem/MISP-RPM#17]
```
+ patch --ignore-whitespace -p0
/var/tmp/rpm-tmp.vdHq5P: line 45: /home/alex/rpmbuild/SOURCES/MISP-Server.php.patch: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.vdHq5P (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.vdHq5P (%install)
```

MISP-Server.php.patch seems to be missing in the repository. Is it still needed and if so, could you add it to the repo?

Thanks a lot!

**Comment by amuehlem** [comment]
Hi Alexander

Yes, it's still needed, it's a small hack that writes the MISP version (git build hash) to the diagnostics page. I've added it to the repository.

Best
Andreas
