### ISSUE TITLE
error: Failed build dependencies: when running ./misp-docker-build-locally.sh

### ISSUE THREAD

**Issue by Quyrean** [amuehlem/MISP-RPM#18]
I am trying to build misp from my local source.  I tried running the file docker/misp-docker-build-locally.sh and got the following errors:

```
$ ./misp-docker-build-locally.sh
...
+ rpmbuild -ba /home/builder/rpm/misp.spec
error: Failed build dependencies:
	python36-devel is needed by misp-2.4.109-1.el7.centos.noarch
	python36-pip is needed by misp-2.4.109-1.el7.centos.noarch
	python36-lxml is needed by misp-2.4.109-1.el7.centos.noarch
	python36-python_dateutil is needed by misp-2.4.109-1.el7.centos.noarch
	python36-six is needed by misp-2.4.109-1.el7.centos.noarch
	python36-setuptools is needed by misp-2.4.109-1.el7.centos.noarch

```

I tried modifying the pkg.misp file like so:

```
sudo yum -y install git libxslt-devel zlib-devel curl wget
sudo yum -y install https://centos7.iuscommunity.org/ius-release.rpm
sudo yum -y install python36-devel python36-pip python36-lxml python36-dateutil python36-six python36-setuptools
```

and got the following error:

```
+ rpmbuild -ba /home/builder/rpm/misp.spec
error: Failed build dependencies:
	python36-python_dateutil is needed by misp-2.4.109-1.el7.centos.noarch
```

I also tried running rpmbuild on the python36-python_dateutil.spec, but got errors trying that also.

 Do you have any instructions on how to build the misp rpm?  thanks.

**Comment by amuehlem** [comment]
Hi Quyrean

I'm no longer using the docker build mechanism as I'm running a koji instance to create all RPMs from the SPEC files. So it's better I remove the docker folder as I'm no longer updating these scripts.

As the dependencies for building all packages are quite a hassle, I compile all packages and offer them in a special repository. Just have a look at the https://github.com/amuehlem/MISP-RPM/blob/master/INSTALL.md Install instructions. You can install all precompiled packages from there.

The build instructions show a bit more details about the sequence in which the packages should be built https://github.com/amuehlem/MISP-RPM/blob/master/BUILD.md.

The python36-python_dateutil.spec just compiled successfully, so this should work. Just have a look at the error output and you should see if any dependencies are missing.

Best
Andreas

**Comment by Quyrean** [comment]
Hi Andreas,

Thank you for the quick response.  Unfortunately, due to my project requirements I cannot use the pre-built package.  I need to actually update some packages to meet security requirements and modify some misp code and build the rpm from my own modified code.

I looked at the build instructions page you linked, but it is just a list of packages, with no instructions.  Do I just do an rpmbuild of each package listed? 

I am unfamiliar with koji.  I tried installing koji, but from the documentation it appears that to run a build I need some kind of fedora contributer account and a kube ticket or I need to setup a webserver.  Do you have any instructions on using koji or a koji config file?

Thank you for the help.
 Jen...

**Comment by amuehlem** [comment]
Hi Jen

Yes, the list is the order in which the packages have to be built and installed to resolve the dependencies for the next package to be built. It is a difficult procedure if you don't have any automation process which helps to simplify this.

I've installed koji on a server and run it standalone in our internal network, there is no fedora account needed. If you want to use the fedora koji infrastructure, you need a fedora developer account. But be careful to build the package on the correct host/distribution where it should run afterwards. I'm not sure you can build packages on a fedora host and run them on a CentOS host afterwards (for example).

Best
Andreas

**Comment by Quyrean** [comment]
Hi Andreas,
Thank you.  That is helpful to know.  We are trying to automate a build, and we want to also be able to keep up with any changes made to MISP or your MISP-RPMs.  We are actually running the pre-built rpms on rhel7 and it seems to work fine.
Do I need a koji config file or does    koji build

work by itself?
thanks,
Jen...

    On Friday, August 16, 2019, 11:48:35 AM CDT, Andreas Muehlemann <notifications@github.com> wrote:  
 
 
Hi Jen

Yes, the list is the order in which the packages have to be built and installed to resolve the dependencies for the next package to be built. It is a difficult procedure if you don't have any automation process which helps to simplify this.

I've installed koji on a server and run it standalone in our internal network, there is no fedora account needed. If you want to use the fedora koji infrastructure, you need a fedora developer account. But be careful to build the package on the correct host/distribution where it should run afterwards. I'm not sure you can build packages on a fedora host and run them on a CentOS host afterwards (for example).

Best
Andreas

**Comment by amuehlem** [comment]
Hi Jen

Koji does all the work by itself, you can just upload the SRPM and it will than start to create the RPM according to the included SPEC file. The nice point about koji is, it creates an internal repository, so every package you created is automatically available for the next build. Like this you just have to start building the packages in the correct order and can proceed until you're ready to create your misp package. Doing this by hand via docker was a big hassle for me.

Best
Andreas

**Comment by ninpo99** [comment]
Andreas,
Working with Jen and wonder if you know whether your process works with BitBucket git repositories?

Thanks,

Gary

**Comment by amuehlem** [comment]
You mean automatically building an RPM based on the code in git? Should work in theory, but to build the RPMs your building host/pipeline needs access to a repository where all the already built RPMs are available for the current build process to solve the dependencies. I'm not sure if bitbucket offers such features.

**Comment by Quyrean** [comment]
Hi Andreas,

Sorry to be dense, but we are stuck.  We have several people working on this but cannot make any progress.  We have read all the guides we can find, but most of them are about compiling Fedora.  

Once we have the koji hub running (I used the koji-dojo), how do we build the rpm?  What is the command line to run?

thanks,

Jen...
