### ISSUE TITLE
Package conflicts during the update & update procedure

### ISSUE THREAD

**Issue by ykorkmaz** [amuehlem/MISP-RPM#21]
Hi,

I encountered problems updating the MISP due to some package conflicts, e.g. python36 with python3   from Centos-BASE.

I had to manually install the conflicting packages from the correct repo. Is there a way to avoid this or an update procedure?

Regards

**Comment by amuehlem** [comment]
Hi

I know, I have to rewrite many of the RPMs Spec files, also because MISP will no longer support python2. For Example, the pymisp package will change quite a lot and I might rewrite many of the SPECs in the next weeks.

Best
Andreas

**Comment by amuehlem** [comment]
python3 is now part of base repositories for CentOS (base) and RHEL (rhel-x86_64-server-7)
