### ISSUE TITLE
version 2.4.120 not available

### ISSUE THREAD

**Issue by MamrK29** [amuehlem/MISP-RPM#22]
Hi There, 

I've been using https://certrepo.switch.ch/certrepo/misp/ to update misp, I was looking to get misp release 2.4.120 but the repo list does not contain it. I was wondering if the list would be updated to contain it?

Thanks,

Mohammad

**Comment by amuehlem** [comment]
Hi Mohammad

I was quite busy the last days and could now build the 2.4.120 package and test it. It's available in the repository. The 2.4.121 Version will follow in the next hour.

Best
Andreas
