### ISSUE TITLE
RPMs for EL8?

### ISSUE THREAD

**Issue by JoeP-oss** [amuehlem/MISP-RPM#25]
Are there plans to create RPMs for RHEL/CentOS 8?

e.g. `php-mysql` has been replaced with `php-mysqlnd` and installation throws two problems:

 Problem 1: cannot install the best candidate for the job
  - nothing provides policycoreutils-python needed by misp-2.4.124-1.el7.noarch
 Problem 2: cannot install the best candidate for the job
  - nothing provides libpqxx needed by misp-modules-1.0-8.el7.noarch

**Comment by amuehlem** [comment]
Hi JoeP-oss

There are plans (or intentions) to do so, unfortunately I currently don't find the time to actively work on the packages. Especially PHP 7.4 generates a lot of work for RHEL/CentOS 7 and 8.

So if you want to participate, feel free to help.

Best
Andreas

**Comment by toddejohnson** [comment]
I think EL8 would make this much easier than EL7 thanks to AppStreams. Would love to have packages instead of install script from source that currently isn't working.

**Comment by amuehlem** [comment]
Hi Todd

Would it be a problem for you if we change to an external repo for PHP? I'm thinking to use https://rpms.remirepo.net/ for PHP 7.4, as building PHP for MISP is quite time-consuming. I'm checking if all needed PHP Modules are available, but think this would reduce my work for the RPMs.

Best Andreas

**Comment by toddejohnson** [comment]
@amuehlem This repo is great! I totally understand using REMI for EL7 to get php 7.x. EL8's AppStreams should make this a moot point as you have 7.2, 7.3 and hopefully when those go EOL 7.4+ I hope. I have high hopes for AppStreams. 

The user should be able to stay RHEL8 proper repos as much as possible for support while still grabbing 3rd party to run MISP where needed. If we use the right provides names the package should support both and use what the user has for repos. 

I think PHP wise php-redis would be the only package you need and the spec for that should be simple. EL7's SCL was a good start but the environments not being global was a pain. 

I need to look at the python modules next. Python36 is native for EL8 so I would suggest focusing on EL8 if possible as core includes most of what is needed and leave EL7 with EL6 for the time being. I'm spoiled with being a fresh install and understand the need to maintain EL7 for existing installs. 

I was going to suggest a branch EL8 where we could try to package only the needed dependencies not provided by RH, EPEL. Or the reverse Branch for EL7 then move master forward with EL8?

Would be nice to get this in EPEL and use their build/hosting. ;-) Right now this is a side project. I hope to present this at work in the next week.

**Comment by JoeP-oss** [comment]
Hi, I just wanted to touch base and see if there was any update on getting an el8 MISP package - sadly I don't have any experience in this area to help on this.

**Comment by JoeP-oss** [comment]
Hi @amuehlem,

Just wondering how this was going, and if you have a (rough) ETA for a production-ready EL8 RPM?

I'm in the process of planning a refresh of our MISP estate and know I'll get push back if I ask for RHEL7; If I need to ask for RHEL7 it will help soften the blow if I can add "... but I should be able to upgrade to RHEL 8 around xxx 202x"

Thanks

**Comment by amuehlem** [comment]
Hi JoeP-oss

I'm working on the EL8 RPMs and hope they will be ready in the next two weeks. The first build looks promising, but here will be some testing needed.

Best

**Comment by amuehlem** [comment]
Hi JoeP-oss

RHEL8 Packages are ready!

https://github.com/amuehlem/MISP-RPM/blob/master/RHEL8.md

Best Andreas
