### ISSUE TITLE
 This page is not working

### ISSUE THREAD

**Issue by easrml** [amuehlem/MISP-RPM#26]
I installed misp through rpm on a CentOS 7 server, and when I'm trying to access the site, I get an error message in the url http://myip/users/change_pw, below is an error message ...

This page is not working
Excessive redirection for 192.168.1.170
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

Could you help me? Tk u!

**Comment by amuehlem** [comment]
Hi

Is your setting 'baseurl' in MISP/app/Config/config.php reflecting the URL your accessing via your browser? Looks like there is some redirection going on and the baseurl is one of the first settings to look at.

Best
Andreas

**Comment by easrml** [comment]
I managed to solve ... restarted the server! even changing the baseurl parameter still remained the problem, but after the boot was solved.

Thank you so much!
