### ISSUE TITLE
MISP task scheduler does not work

### ISSUE THREAD

**Issue by Tyrell20** [amuehlem/MISP-RPM#29]
Hello,
I am facing an issue with the task scheduler set via GUI.
It does not fetch feeds and it reports the error below:
"Could not fetch feed."

Checking the log file  resque-worker-error.log
I found error below:
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). 

No error via the option "Fetch all feed and store data" under "List Feeds" section starting manually.

Many thanks for your support

**Comment by amuehlem** [comment]
Hi Tyrell

Have you checked the MISP docs? The Taskscheduler is known to be quite buggy, from what I know, the developers propose to automate tasks via the CLI.

https://test-misp.switch.ch/events/automation/#console_admin_tasks

Which feeds are activated when they should be fetched by the task scheduler?

**Comment by amuehlem** [comment]
no answer
