### ISSUE TITLE
Install gpgkey and https

### ISSUE THREAD

**Issue by easrml** [amuehlem/MISP-RPM#31]
Hi Guys,

how can i install gpgkey on MISP? Can I install following the office manual? Or do you have any tips?

Other question about install https on MISP, do you have a tips?

Thank you!

**Comment by aungthurhahein** [comment]
I tried several ways to generate gpgkey but it didn't work. permission denied error.

**Comment by amuehlem** [comment]
Hi easrml

HTTPS must be enabled on apache (https://httpd.apache.org/docs/2.4/ssl/). The gpgkey can be installed following the MISP manual.

**Comment by amuehlem** [comment]
> I tried several ways to generate gpgkey but it didn't work. permission denied error.

Where do you get the permission denied error? In MISP or on the command line?

**Comment by aungthurhahein** [comment]
@amuehlem @JoeP-oss Thanks guy.. a bit of tweak based on your script and it works fine for my MISP setup.
