### ISSUE TITLE
How to add misp expansion modules?

### ISSUE THREAD

**Issue by aungthurhahein** [amuehlem/MISP-RPM#32]
I was figuring out a way to add some missing modules from this repo:https://github.com/MISP/misp-modules.

I added the file to python MISP-modules path and restart Dameon and services but didn't see the new module added.

Any idea on how to achieve this?
Thanks.

**Comment by amuehlem** [comment]
How did you add the missing modules? They must be within the python paths to be found by the misp-modules daemon.

**Comment by aungthurhahein** [comment]
@amuehlem I added a new python file in /usr/lib/python3.6/site-packages/misp_modules/modules/exapnsion.
Afterward, I restarted the misp modules services but it didn't show up in the MISP web UI.
Any help is appreciated and I am new to MISP as well.

**Comment by amuehlem** [comment]
Have you added your module to the __init__.py file in the same directory?

/usr/lib/python3.6/site-packages/misp_modules/modules/expansion/__init__.py

See https://github.com/MISP/misp-modules#how-to-add-your-own-misp-modules
