### ISSUE TITLE
Post Install Suggestions

### ISSUE THREAD

**Issue by JoeP-oss** [amuehlem/MISP-RPM#33]
I've been working to reduce the number of errors on the diagnostics page from a clean install form the RPM; I have manged to consistently fix the missing ssdeep and zip PHP modules, outdated Python modules, and the PHP memory limit, on RHEL and CentOS, using the below.

I don't know if you can/want to fold into the RPM or add to the install guide.

```bash
# install php-ssdeep
yum install ssdeep-devel autoconf gcc -y -q
ln -s /usr/lib64/libfuzzy.so /usr/lib/libfuzzy.so
pecl channel-update pecl.php.net >/dev/null
pecl install ssdeep >/dev/null
echo extension=ssdeep.so | tee -a /etc/php.d/php.ini
# install php-zip
yum install http://packages.psychotic.ninja/7/plus/x86_64/RPMS/libzip-0.11.2-6.el7.psychotic.x86_64.rpm -y -q
yum install http://packages.psychotic.ninja/7/plus/x86_64/RPMS/libzip-devel-0.11.2-6.el7.psychotic.x86_64.rpm -y -q
pecl install zip >/dev/null
echo extension=zip.so | tee -a /etc/php.d/php.ini
# restart Apache to load modules
systemctl restart httpd
# Upgrade Python dependencies
pip3 install --upgrade stix >/dev/null
pip3 install --upgrade stix2 >/dev/null
pip3 install --upgrade pymisp >/dev/null
# Up PHP memory limit
echo "memory_limit = 2048M" | tee -a /etc/php.d/php.ini
```

The Psychotic Ninja repo is a Community Approved Repository according to [CentOS documentaiton](https://wiki.centos.org/AdditionalResources/Repositories).

**Comment by amuehlem** [comment]
Hi JoeP-oss

Thank you for your propositions! I'll work on the RPM next week during the OSSS hackathon http://hackathon.hack.lu/ and I hope to work on the RPMs for MISP on RHEL 8. There I'll add your input. I might also be able to add this to the current RPMs for RHEL7.

**Comment by Tyrell20** [comment]
Hello, 
@amuehlem  do you think it will be available for all installation via future RPM update?

**Comment by amuehlem** [comment]
Hi Tyrell

I'm working on MISP RPMs for RHEL8 / CentOS 8, I hope to be able to fix most of them.

Regarding configuration settings, I'm using ansible to install and configure MISP, such settings will not all be handled by the RPMs.

**Comment by amuehlem** [comment]
All submodules for MISP are now included in an python virtual environment, like this the correct versions will be installed during the build process.

Config settings will not be included in the RPMs, these should be set via ansible / puppet or manually.
