### ISSUE TITLE
Download Issue - Ignoring "type"

### ISSUE THREAD

**Issue by muralivenkataraman** [amuehlem/MISP-RPM#38]
Hi there,

I am trying to download a csv file with certain types like "ip-dst, ip-dst|port, domain, sha256" and running into issues.  The type filter is ignored and getting all events downloaded to a csv file.

OS Version: CentOS 7.8
MISP Version: 2.4.132
curl: 7.29

Here is the curl statement and also the body of the request.

`
curl -k -v -XPOST https://hostname/events/csv/download -H "Authorization: token" -H "Content-Type: application/json" -d @misp.json

{"ignore": "True", "tags": ["osint:source_type="block-or-filter-list""], "type": ["ip-dst", "domain", "sha256", "ip-dst|port"],
"last": "30d"}

Screen shot

![image](https://user-images.githubusercontent.com/51952725/96924676-fdb81080-1480-11eb-9b67-a8762f447f3c.png)

**Comment by muralivenkataraman** [comment]
Hi There,

Anyone had a chance to look at this issue ?

Thanks
Murali

**Comment by amuehlem** [comment]
Looks like a MISP related issue and not related to the RPM. You should report it on the MISP project https://github.com/MISP/misp

**Comment by muralivenkataraman** [comment]
Hi Andreas,

Thank  you :-).  I will open an issue with them.

Thanks
Murali
