### ISSUE TITLE
RHEL 7.9. - RPM - can't install misp_modules

### ISSUE THREAD

**Issue by walkergregt** [amuehlem/MISP-RPM#39]
1. Tried to install MISP RPM on RHEL 7.9 using RPM with this command:

sudo yum install misp-modules

Error message says did not include 4 GLIBC values.

***
Running transaction check
ERROR with transaction check vs depsolve:
libc.so.6 is needed by misp-modules-2.4.121-2.el7.x86_64
libc.so.6(GLIBC_2.0) is needed by misp-modules-2.4.121-2.el7.x86_64
libc.so.6(GLIBC_2.1) is needed by misp-modules-2.4.121-2.el7.x86_64
libc.so.6(GLIBC_2.1.3) is needed by misp-modules-2.4.121-2.el7.x86_64
libc.so.6(GLIBC_2.4) is needed by misp-modules-2.4.121-2.el7.x86_64
 You could try running: rpm -Va --nofiles --nodigest
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2020-10-21.13-25.36ePQK.yumtx
***

2. These symbols do not exist in libc.06

***
strings /usr/lib64/libc.so.6 |grep ^GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_PRIVATE
GLIBC_2.8
GLIBC_2.5
GLIBC_2.9
GLIBC_2.7
GLIBC_2.6
GLIBC_2.11
GLIBC_2.16
GLIBC_2.10
GLIBC_2.17
GLIBC_2.13
GLIBC_2.2.6
***

3. Possible to update RPM to fix?

**Comment by amuehlem** [comment]
There was a dependency for glibc.i686 missing. I just pushed misp-modules-2.4.121-3.el7.x86_64.rpm to the repository, can you try to install this version?

**Comment by walkergregt** [comment]
Please see attached.
[RHEL 7.9. - RPM - can't install misp_modules #39.txt](https://github.com/amuehlem/MISP-RPM/files/5452308/RHEL.7.9.-.RPM.-.can.t.install.misp_modules.39.txt)

**Comment by sbennett12006** [comment]
Just tried to install on Centos 7 and also got the glibc.i686 error message.

Error: Package: misp-modules-2.4.121-3.el7.x86_64 (misp)
           Requires: glibc.i686

**Comment by amuehlem** [comment]
Ah, my bad. Yum accepts glibc.686 to install the 32bit version, but in the SPEC file this dependency must be declared as glibc(x86-32). I've created the misp-modules-2.4.121-4.el7.x86_64 package and pushed it to the repository. In a test it successfully installed glibc.i686 as a dependency.

**Comment by muralivenkataraman** [comment]
Hi Andreas,   

How do we install/update to the latest version, 2.4.133?   

Thanks
Murali

**Comment by amuehlem** [comment]
MISP or misp-modules?

**Comment by kvmuralidhar** [comment]
Hi Andreas,

misp-modules.  

Thanks
Murali

**Comment by amuehlem** [comment]
Hi Murali
misp-modules 2.4.121 is the newest version, see the tags in the project https://github.com/MISP/misp-modules/tags

Best
Andreas

**Comment by kvmuralidhar** [comment]
Hi Andreas,

Hah, thank you.

Murali

**Comment by sbennett12006** [comment]
Andreas,

Just for the record, the misp-modules-2.4.121-4.el7.x86_64 package did installed perfectly for me in CentOS 7.

Thanks for your help.

**Comment by walkergregt** [comment]
Yes, misp-modules-2.4.121-4.el7.x86_64 package installed successfully for me as well.
