### ISSUE TITLE
Update MISP from 2.4.132 to 2.4.134

### ISSUE THREAD

**Issue by muralivenkataraman** [amuehlem/MISP-RPM#40]
Hi,

I am running 2.4.132 and how do I update this to the latest version?  I see this under server settings/maintenance and if I click on update, it throws an error.

MISP version
Every version of MISP includes a json file with the current version. This is checked against the latest tag on github, if there is a version mismatch the tool will warn you about it. Make sure that you update MISP regularly.

Currently installed version… v2.4.132 (90517f591b6f37960e78dcdf7d4c6245baf78821)
Latest available version… v2.4.134 (a2e393b1b98b6c79ac033fba04e73a444af7b839)
Status… Outdated version
Current branch… You are not on a branch, Update MISP will fail

`cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1

error: pathspec 'app/composer.json' did not match any file(s) known to git.

cd $(git rev-parse --show-toplevel) && git pull origin  2>&1

error: pathspec 'app/composer.json' did not match any file(s) known to git.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

=================================

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1

`

Thanks
Murali

**Comment by amuehlem** [comment]
Hi Murali

You can update the packages like any other RPM. I've created the new 2.4.134 and pushed it to the repository, you can install it from there.

Just a side-note. The RPMs will not follow every commit on github, so there might be newer versions within the 24.134 version as well. On the other hand the RPMs provide exactly the same code base, if you're following a string testing - production setup.

If you really want to have the latest commit from github on your system, installing it from git will be the better solution.

Best
Andreas

**Comment by muralivenkataraman** [comment]
Hi Andreas,

That worked :).

Thanks
Murali
