### ISSUE TITLE
issue installing MISP 

### ISSUE THREAD

**Issue by benjaminholloway** [amuehlem/MISP-RPM#41]
Hi, im having some trouble installing MISP. I am running centos8 vm fresh install updated with the epel repo enabled and the misp repo. there is nothing else on centos8. when i sudo yum install php-mysql i get an error 
unable to find a match: php-mysql.  can i just install mariadb-service.

Also if i skip that for now and try to yum install misp I get another error. 
![MispIssue](https://user-images.githubusercontent.com/50229490/103928549-e8639180-5113-11eb-8fb4-1f86973ed959.PNG)

if i use yum --enablerepo=misp install misp I get the same error.

Also can i install as root? or should it be user named misp?

thanks in advance for any help you can give me with this.

**Comment by amuehlem** [comment]
Hi Benjamin

It looks you try to install misp-2.4.136-1.el7.noarch (which is built for Centos7) on a CentOS 8 host. This will not work. I hadn't had much time to work on the CentOS 8 packages, so they are not ready yet.

**Comment by benjaminholloway** [comment]
Ok. Thank you so much for clarifying that for me.
