### ISSUE TITLE
MISP no space on /var/www/MISP/app

### ISSUE THREAD

**Issue by Tyrell20** [amuehlem/MISP-RPM#43]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Red Hat Enterprise Linux Server release 7.9 (Maipo)
| MISP version / git hash   | 2.4.137

### Support Questions
Hello,
we are facing an issue about the space left on /var/www/MISP/app.
The file stored here take up the following space:

> 4.0K    composer.json
4.0K    composer.license
92K     composer.lock
2.2M    composer.phar
84K     Config
176K    Console
1.8M    Controller
3.0G    files
4.0K    index.php
13M     Lib
12M     Locale
4.0K    Makefile
2.5M    Model
356K    Plugin
36K     Test
1.2G    tmp
4.0K    update_thirdparty.sh
12M     Vendor
3.8M    View
15M     webroot

Could you please indicate me how to manage the file stored here?

Many thanks

**Comment by amuehlem** [comment]
files are attachments etc. from events, I think you do not want to delete them. In tmp you might be able to clean up a bit, but you should check with the [MISP creators](https://github.com/MISP/MISP) what can be deleted there.

As the the space used by misp is heavily dependent on the number of events you have in your instance you should have enough space available for the database and events (with attachments).

**Comment by Tyrell20** [comment]
Hi @amuehlem many thanks for your feedback.
The more space is located on the following path:
- /var/www/MISP/app/files/scripts/tmp 

Here I found also event in stix format.
It is not clear if I can to delete these file.

Many thanks again

**Comment by amuehlem** [comment]
The MISP team should be able to help!

**Comment by Tyrell20** [comment]
Thanks @amuehlem I also opened the ticket there.
