### ISSUE TITLE
update php & python

### ISSUE THREAD

**Issue by garanews** [amuehlem/MISP-RPM#47]
Any chance to upgrade those 2 components?

php 7.2
python 3.6

**Comment by amuehlem** [comment]
I'm working to switch to the RPM Packages from https://blog.remirepo.net/ and will update the installation instructions as soon as possible. Python3.6 is provided by RedHat / CentOS, you'll get the current versions from them. Or do you expect an newer version of python like python 3.9?

**Comment by garanews** [comment]
So python 3.6 ok.
Also lief should be updated, from 0.9.0 to 0.11.4 .

**Comment by amuehlem** [comment]
lief-python is now on version 0.11.4.

**Comment by amuehlem** [comment]
With MISP 2.4.145 im changing how the RPMs are created. All python modules and libraries are packed into a python virtual environment. Like this it is easier to keep them up 2 date. Have a look at https://github.com/amuehlem/MISP-RPM/blob/master/UPGRADE.md
