### ISSUE TITLE
Update MISP instance installed through RPM

### ISSUE THREAD

**Issue by davecabio** [amuehlem/MISP-RPM#48]
Good morning,

maybe it's a strange request: 
which is the best way to update a MISP instance installed through this RPM? 
It's not possible to update it through git, which is normal I think, but I can't find documentation to update a working instance without risk.

Thanks

**Comment by amuehlem** [comment]
Hi davecabio

You can just upgrade using the newest RPM from our repository. Depending on the currently installed verion, it could make sense to upgrade step by step (one version after the other).
From my experience, there are no big issues to expect. Just have a look at the Page "Server Settings & Maintenance" -> Diagnostics page under "Schema status". I had to resolve some of the DB changes using the provided SQL statements.
