### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by Deadshot-MISP** [amuehlem/MISP-RPM#51]
My linux is a bit rusty, so just two quick questions

1. Doing a fresh installation, what is the correct command to point to the update version of MISP (yum install https://certrepo.switch.ch/certrepo/misp/misp-release-1.0-5.el7.noarch.rpm)

2. I am installing this in an air gapped network so will I need a Firewall rule to certrepo.switch.ch or can this be access through a redhat satellite update server

**Comment by amuehlem** [comment]
The repository contains the updated versions as well. After installing the current version, you can update the MISP RPM with the following updated version as any other RPM.

The RPMs are only available on certrepo.switch.ch and not through a RedHat satellite Server. Maybe you can include this repo into your satellite server, but I'm not an satellite expert.

**Comment by Deadshot-MISP** [comment]
so would I simply just run this command? 
yum install https://certrepo.switch.ch/certrepo/misp/

**Comment by amuehlem** [comment]
No, the Installation instructions are linked on the README page

https://github.com/amuehlem/MISP-RPM/blob/master/INSTALL.md
