### ISSUE TITLE
Outdated PyMISP package

### ISSUE THREAD

**Issue by racco42** [amuehlem/MISP-RPM#52]
Hi,

would it be possible to create new python36-pymisp package with updated version of PyMISP? The MISP already complains that the version is outdated on the diagnostic page and also some modules requires newer version.

Thank you!

**Comment by amuehlem** [comment]
Hi Racco42

With MISP 2.4.145 I'm changing the way how the RPMs are created. All Python modules are packed into a python virtual environment, like this it is easier to update pymisp etc. to the current version. Like this there is no python36-pymisp RPM needed.

Please have a look at the upgrade instructions https://github.com/amuehlem/MISP-RPM/blob/master/UPGRADE.md
