### ISSUE TITLE
No package misp-python-virtualenv available.

### ISSUE THREAD

**Issue by JoeP-oss** [amuehlem/MISP-RPM#55]
Following https://github.com/amuehlem/MISP-RPM/blob/master/UPGRADE.md I am able to successfully upgrade, however, the `misp-python-virtualenv` package does not appear to be available, so I cannot switch it using the venv.

**Comment by amuehlem** [comment]
Ups, I had to rebuild the repository.

The download should work now.

**Comment by JoeP-oss** [comment]
Package now available, thanks.

One tip for you upgrading doc, users will need to do `yum install misp-python-virtualenv`' otherwise yum returns `Package(s) misp-python-virtualenv available, but not installed.`

**Comment by amuehlem** [comment]
Thank you for the hint, I've updated the docs
