### ISSUE TITLE
Upgrade to v2.4.146 Failing with Dependency Errors

### ISSUE THREAD

**Issue by Tyrell20** [amuehlem/MISP-RPM#56]
Hello,

I'm currently unable to upgrade to the v2.4.146 from v2.4.144 on RHEL 7.9, I'm getting the following output by following the official procedure https://github.com/amuehlem/MISP-RPM/blob/master/UPGRADE.md.

After the installation of the package "misp-python-virutalenv", the "yum upgrade misp" command returns this error:

Loaded plugins: product-id, rhnplugin, search-disabled-repos, subscription-manager
This system is receiving updates from RHN Classic or Red Hat Satellite.
Resolving Dependencies
--> Running transaction check
---> Package misp.noarch 0:2.4.144-1.el7 will be updated
---> Package misp.x86_64 0:2.4.146-1.el7 will be an update
--> Processing Dependency: php74-php-xml for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-zip for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-ssdeep for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-redis5 for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-rdkafka for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-gnupg for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pdo for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-opcache for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-mysqlnd for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-mbstring for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-json for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-intl for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-gd for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-cli for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-brotli for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-bcmath for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: gtcaca for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: faup for package: misp-2.4.146-1.el7.x86_64
--> Running transaction check
---> Package faup.x86_64 0:1.6-1.el7 will be installed
---> Package gtcaca.x86_64 0:0+gitb05ed3c-2.el7 will be installed
--> Processing Dependency: libcaca for package: gtcaca-0+gitb05ed3c-2.el7.x86_64
--> Processing Dependency: libcaca.so.0()(64bit) for package: gtcaca-0+gitb05ed3c-2.el7.x86_64
---> Package misp.x86_64 0:2.4.146-1.el7 will be an update
--> Processing Dependency: php74-php-xml for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-zip for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-ssdeep for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-redis5 for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-rdkafka for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-gnupg for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pdo for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-opcache for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-mysqlnd for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-mbstring for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-json for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-intl for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-gd for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-cli for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-brotli for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-bcmath for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php for package: misp-2.4.146-1.el7.x86_64
--> Running transaction check
---> Package libcaca.x86_64 0:0.99-0.17.beta17.el7 will be installed
--> Processing Dependency: libGLU.so.1()(64bit) for package: libcaca-0.99-0.17.beta17.el7.x86_64
--> Processing Dependency: libglut.so.3()(64bit) for package: libcaca-0.99-0.17.beta17.el7.x86_64
---> Package misp.x86_64 0:2.4.146-1.el7 will be an update
--> Processing Dependency: php74-php-xml for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-zip for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-ssdeep for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-redis5 for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-rdkafka for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-gnupg for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pdo for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-opcache for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-mysqlnd for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-mbstring for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-json for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-intl for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-gd for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-cli for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-brotli for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-bcmath for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php for package: misp-2.4.146-1.el7.x86_64
--> Running transaction check
---> Package freeglut.x86_64 0:3.0.0-8.el7 will be installed
---> Package mesa-libGLU.x86_64 0:9.0.0-4.el7 will be installed
---> Package misp.x86_64 0:2.4.146-1.el7 will be an update
--> Processing Dependency: php74-php-xml for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-zip for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-ssdeep for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-redis5 for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-rdkafka for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pecl-gnupg for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-pdo for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-opcache for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-mysqlnd for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-mbstring for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-json for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-intl for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-gd for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-cli for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-brotli for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php-bcmath for package: misp-2.4.146-1.el7.x86_64
--> Processing Dependency: php74-php for package: misp-2.4.146-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-pecl-zip
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-mysqlnd
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-opcache
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-gd
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-json
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-intl
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-cli
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-pecl-redis5
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-pecl-gnupg
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-pdo
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-pecl-rdkafka
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-mbstring
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-bcmath
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-pecl-ssdeep
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-brotli
Error: Package: misp-2.4.146-1.el7.x86_64 (misp)
           Requires: php74-php-xml
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Could you please help us?
Thank you

**Comment by amuehlem** [comment]
Hi Tyrell

It seems, yum does not find the php packages.

Please check the following files exist:
* /etc/yum.repos.d/remi*.repo

This files are needed to find the PHP packages in question

* run `yum clean all`
to make sure, all yum caches are cleaned

Than you should be able to install the misp-2.4.146 RPM.

Best
Andreas

**Comment by Tyrell20** [comment]
Hi amuehlem,

you're right, after added the remi repo it worked.

Thank you
