### ISSUE TITLE
MISP Repo returns 404's for misp-release-1.1-1.el7.noarch.rpm

### ISSUE THREAD

**Issue by darkorb** [amuehlem/MISP-RPM#57]
It appears that recently (today at least) the download sources are returning 404's for the repo data and also the misp-release-1.1-1.el7.noarch.rpm used during the initial install. Have checked from a number of connections and the same occurs from all of them.

```
➜  ~ curl -I https://certrepo.switch.ch/certrepo/misp/misp-release-1.1-1.el7.noarch.rpm
HTTP/2 404
server: nginx/1.20.1
date: Wed, 14 Jul 2021 23:24:43 GMT
content-type: text/html
content-length: 153
```

Thanks!

**Comment by amuehlem** [comment]
HI darkrob

Thank you for point this, there was a problem with our repo server, our admin was able to fix it and the RPMs are available.

by the way, I made small changes to the misp-release RPM, you can install the misp-release-1.1-2.el7.noarch.rpm. Documentation is updated accordingly.

Best
Andreas
