### ISSUE TITLE
v2.4.152: Diagnostics Page 500 Error

### ISSUE THREAD

**Issue by JoeP-oss** [amuehlem/MISP-RPM#61]
The RPM of 2.4.152 contains a bug that prevents the diagnostics page from displaying, this has been fixed upstream with the same version number, please can a new package be released? 

See MISP/MISP#8078 and MISP/MISP#8057.

Thanks

**Comment by amuehlem** [comment]
Hi JoeP-oss

I've created a new RPM 2.4.152-2, git commit version is 4f881c8248daa73db09e295650887a8122404285.

Can you check if the new release solves the issue?

On my test instance I see an error ```Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sub' in 'field list'``` but am not sure if this is related to this issue or something else.

**Comment by amuehlem** [comment]
the error I mentioned seem not related to the diagnostics page error, I found another test system and could verify 2.4.152-2 works without any issues
