### ISSUE TITLE
PHP Modules: posix and apcu

### ISSUE THREAD

**Issue by JoeP-oss** [amuehlem/MISP-RPM#62]
I've noticed that posix and apcu have been added as optional PHP modules for MISP on the diagnostics page, but aren't currently installed with MISP-RPM.

* posix: For process info fetching.
* apcu: To cache data in memory instead of file system.

Can these be added to the dependencies in a future release?

**Comment by amuehlem** [comment]
Thank you for the proposition, I'm adding them to the misp-2.4.153 RPM as requirements.
