### ISSUE TITLE
Misp-modules service can not start after package upgrade to MISP 2.4.157

### ISSUE THREAD

**Issue by alainsilva** [amuehlem/MISP-RPM#64]
MISP-Modules can not start after upgrade from MISP 2.4.156 to 2.4.157 version.

systemctl status misp-modules -l
● misp-modules.service - MISP enhancement modules
   Loaded: loaded (/etc/systemd/system/misp-modules.service; enabled; vendor preset: disabled)
   **Active: activating** (auto-restart) (Result: core-dump) since Wed 2022-04-06 09:06:00 -03; 48s ago
  Process: 18882 ExecStart=/var/www/cgi-bin/misp-modules-venv/bin/misp-modules (code=dumped, signal=ABRT)
 Main PID: 18882 (code=dumped, signal=ABRT)
   CGroup: /system.slice/misp-modules.service

Apr 06 09:06:00 myserver systemd[1]: misp-modules.service: main process exited, code=dumped, status=6/ABRT
Apr 06 09:06:00 myserver systemd[1]: Unit misp-modules.service entered failed state.
Apr 06 09:06:00 myserver systemd[1]: misp-modules.service failed.

I renamed the py files but the service can not start yet.

/var/www/cgi-bin/misp-modules-venv/lib/python3.9/site-packages/**misp_modules-1.0-py3.9.egg**/misp_modules/modules/expansion

ocr_enrich.py.disabled pdf_enrich.py.disabled qrcode.py.disabled

**Comment by amuehlem** [comment]
Which version of RHEL/CentOS are you using?

**Comment by alainsilva** [comment]
I use Oracle Linux 7.6

Solution reported: https://github.com/amuehlem/MISP-RPM/issues/59

Works fine! Thanks a lot!

Results:

[root@myserver expansion]# systemctl status misp-modules
● misp-modules.service - MISP enhancement modules
   Loaded: loaded (/etc/systemd/system/misp-modules.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-04-06 11:23:23 -03; 7s ago
 Main PID: 24109 (misp-modules)
   CGroup: /system.slice/misp-modules.service
           └─24109 /var/www/cgi-bin/misp-modules-venv/bin/python3 /var/www/cgi-bin/misp-modules-venv/bin/misp-modules
