### ISSUE TITLE
Typo in INSTALL.md

### ISSUE THREAD

**Issue by romahony22** [amuehlem/MISP-RPM#65]
You say yum install misp misp-python-virutalenv misp-modules
virtual is spelt incorrectly in misp-python-virutalenv

Also it probably is a good idea to have at the start 

sudo yum install xorg-x11-font-utils

otherwise the following errors will happen during install

/var/tmp/rpm-tmp.ErkEUE: line 1: mkfontscale: command not found
/var/tmp/rpm-tmp.ErkEUE: line 2: mkfontdir: command not found

**Comment by romahony22** [comment]
RHEL 7

**Comment by amuehlem** [comment]
Could not reproduce the issue with xorg-x11-font-utils.
