### ISSUE TITLE
Security Update v2.4.158 Unavailable

### ISSUE THREAD

**Issue by JoePJisc** [amuehlem/MISP-RPM#66]
v2.4.158 of MISP was released nearly a week ago, the release notes state it is a security release, so I'm keen to roll it out ASAP; is there an estimate on whne the RPM will be available?

I'm seeing the following when running `yum check-update`:

```
misp.x86_64    2.4.157-1.el7    misp
misp-modules.x86_64    2.4.156-1.el7    misp
misp-python.x86_64    3.9.9-6.el7    misp
misp-python-virtualenv.x86_64    2.4.157-1.el7    misp
```

Thanks

**Comment by JoeP-oss** [comment]
Different error and version, but same issue, on AlmaLinux 8 (RHEL8):

```
Error: 
 Problem: cannot install the best update candidate for package misp-python-virtualenv-2.4.157-1.el8.x86_64
  - nothing provides /opt/python/cp38-cp38/bin/python3.8 needed by misp-python-virtualenv-2.4.158-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by amuehlem** [comment]
Hi JoeP-oss

Thank you for pointing this out! I've removed the requirements for /opt/python/cp3* on both RHEL7 and RHEL8 version. I could verify it now installs without the error.

I could not reproduce the 'php > ('0', '7.0', None)' errors, are you installing the RPMs on a CentOS 7 or RHEL7 host?

**Comment by JoeP-oss** [comment]
All sorted, apologies forgot to update
