### ISSUE TITLE
RHEL-only

### ISSUE THREAD

**Issue by adulau** [amuehlem/MISP-RPM#68]
Hi @amuehlem,

Thanks a lot for your work. We did a new version for RHEL-only 

https://github.com/MISP/MISP-RPM - including a release of the RPMS at https://github.com/MISP/MISP-RPM/releases/tag/2.4.158-1

It's a fork of your repository with a different branch for the RHEL-only. Thanks to @remil1000 for the hard work. 

If you have any ideas or feedback, don't hesitate.

We will try to keep this branch inline with your updates too.

**Comment by amuehlem** [comment]
I took over the task, unforked the MISP/MISP-RPM repo and will now upload the RHEL-only packages directly.
