### ISSUE TITLE
libpoppler-cpp

### ISSUE THREAD

**Issue by tonster76** [amuehlem/MISP-RPM#69]
I had to add

dnf --enablerepo=powertools install poppler-cpp

To avoid a poppler error when running
dnf install misp-modules

**Comment by amuehlem** [comment]
Hi tonster76

On which Distribution / Version did you have the issue? I checked with RHEL8 and added the needed code on the [RHEL8 Install doc](https://github.com/amuehlem/MISP-RPM/blob/master/RHEL8.md)

**Comment by amuehlem** [comment]
no updated since Nov 2022
