### ISSUE TITLE
Could not save freetext feed data for feed

### ISSUE THREAD

**Issue by Tyrell20** [amuehlem/MISP-RPM#70]
**Expected behavior**
Feech of all feeds successfully completed.

**Actual behavior**
The feetch of some feeds goes in error:
2022-06-30 10:21:16 Error: Could not save freetext feed data for feed 95.

**Steps to reproduce**
Manual or automatic execution of fetch all events from a feed.

**MISP Version**
2.4.159

**Operating System**
Red Hat Enterprise Linux Server 7.9

PHP version
7.4

**Relevant log output**
[PDOException] SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'id' at row 1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(914): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Correlation.php(308): Mysql->insertMulti()
#2 /var/www/MISP/app/Model/Correlation.php(431): Correlation->__saveCorrelations()
#3 /var/www/MISP/app/Model/Attribute.php(443): Correlation->afterSaveCorrelation()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Attribute->afterSave()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1754): Model->_doSave()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2352): Model->save()
#8 /var/www/MISP/app/Model/Feed.php(1327): Model->saveMany()
#9 /var/www/MISP/app/Model/Feed.php(1189): Feed->saveFreetextFeedData()
#10 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downloadFromFeedInitiator()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#14 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#15 {main}

**Comment by amuehlem** [comment]
Hi Tyrell20

This sounds like an issue with MISP application itself. Maybe you want to report it there? Or is it really related to the RPM?

The 'numeric value out of range' sounds a bit like a database issue (without having all the details).

Best
Andreas

**Comment by Tyrell20** [comment]
Hi Andreas,

I opened a case in the MISP official project also.

I was hoping for help here as well, since this project is a bit more responsive in responding to the issue or support request :)

Is there anything else we can check to give you more details?

Thanks a lot

**Comment by amuehlem** [comment]
Settings of the feed that doesn't work would be helpful, maybe I can find the issue.

**Comment by amuehlem** [comment]
Hm, I could add this feed without any problems.

Can you check the Schema status under diagnostics does not show any DB schema issues?

/servers/serverSettings/diagnostics, somewhere in the middle of the page you should see the SQL database status and Schema status.

**Comment by amuehlem** [comment]
duplicate values in an index are difficult to solve, there is no general solution to this issue. You should open an issue with the MISP project, they should be able to help.
