### ISSUE TITLE
Redis Sessions blocked by local apache config

### ISSUE THREAD

**Issue by JoeP-oss** [amuehlem/MISP-RPM#72]
I've just got to the bottom of not being able to get MISP to use redis sessions when deployed through the RPM (see https://github.com/MISP/MISP/issues/8482).

Simply updating these lines to `/etc/opt/remi/php74/php.ini` as advised will not work:
```ini
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:6379"
```

These lines need to be commeneted out in `/etc/httpd/conf.d/php74-php.conf`:
```conf
php_value session.save_handler "files"
php_value session.save_path    "/var/opt/remi/php74/lib/php/session"
```

Not sure why remi forces files as the session handler, as all seems fine with redis sessions.

If the RPM could make those two changes by defualt that'd be good.

**Comment by amuehlem** [comment]
Hi JoeP-oss

The RPMs will not resolve all configuration issues, just provide a more or less good starting point. I advice to combine the RPMs with a config solution like ansible which is better suited to take care of all configurations (especially if they are provided by different RPM providers).

**Comment by amuehlem** [comment]
Just an idea: we could add a best-practices document gathering such important details and simplifying the configuration process. What do you think, could this help?

**Comment by JoeP-oss** [comment]
I think that's be a really useful addition, I often point people to MISP-RPM for an easy way to install and maintain MISP.

I've got a list somewhere with a number of post install things to do, I will dig it out when I get chance and post a summary here

**Comment by amuehlem** [comment]
I've created the page and added the redis session settings.
