### ISSUE TITLE
MISP not updating - RHEL 8 (RPM Packages)

### ISSUE THREAD

**Issue by iZAK328** [amuehlem/MISP-RPM#73]
Hi, 

I'm currently running a MISP instance (version **_2.4.163_**) using RPM packages on a RHEL 8.6 server. I saw that the latest version on the Github page was found to be **_2.4.164_**. 

- On checking the "Server Settings & Maintenance" page on the web UI, it showed me the following error. 
![MISPUpdateError](https://user-images.githubusercontent.com/33455711/199159569-c6279c56-b0d6-4d55-873c-d66fa19eddd5.png)

1. Could this be because the installation was done using an RPM packages ?
2. Are the RPM packages released separately from the main git repo ?

Also, at the time of the installation, the MISP version was _**2.4.154**_ which had undergone updates all the way till _**2.4.163**_ after which it threw the above error. 

- Current version of MISP
![MISPVersion](https://user-images.githubusercontent.com/33455711/199160132-bcdd30b4-4b8c-43b5-ac70-ca1d97928fdf.png)

**Comment by amuehlem** [comment]
Hi iZAK328

Looks like I forgot to sync the repo after the last build. I re-synced and now you should be able to install version 2.4.164.

The status page checks the current installed version and the latest version via a HTTPS request to Github. Can your server access the internet (e.g. https://api.github.com/repos/MISP/MISP/commits?per_page=1)?

The branch will always generate an error, as the RPMs are not using the built in update mechanism but will install the version packaged in the RPMs.

Best
Andreas

**Comment by iZAK328** [comment]
Hi Andreas, 

Thanks for your quick response. Yes I had updated to the latest version _**2.4.164**_ and it seems to be working fine. 

Thanks!
