### ISSUE TITLE
/users/login page not found (Redhat 8.6)

### ISSUE THREAD

**Issue by w5334221234555** [amuehlem/MISP-RPM#74]
OS: Redhat 8.6

Hi, 
I followed the instruction in the links below and installed MISP on my Redhat 8.6 server.
https://github.com/amuehlem/MISP-RPM
https://github.com/amuehlem/MISP-RPM/blob/master/RHEL8.md
Also, I set "/var/www/MISP/app/webroot" as DocumentRoot in /etc/httpd/conf/httpd.conf, and kept 'baseurl' as blank in /var/www/MISP/app/Config/config.php.

When I tried to connect to MISP, it was redirected to https://url/users/login with 404 error message(Not Found
The requested URL was not found on this server.)
By the way, the error log(/var/www/MISP/app/tmp/logs/error.log) shows nothing.

I tried to reboot the server and restart the services several times but with no success.

Could you provide some advice to deal with this issue?
Thank you.

**Comment by amuehlem** [comment]
Hi

Have you set ```baseurl``` in config.php to something like 'https://example.com'? The redirect to https://url/  shows the baseurl could not be correct.

Best
Andreas

**Comment by w5334221234555** [comment]
By the way, there might be a slight error with the command in the Simple Background jobs section(https://github.com/amuehlem/MISP-RPM).
`supervisorctl -h http://localhost:9001 -u supervisor -p securePasswordHere status`

Since `-h` is for help, should it be `-s`(serverurl)?

Thank you.

**Comment by w5334221234555** [comment]
Hi, 

I used https://url/users/login at first just to mask the url.
My issue is that I set baseurl as '' in the first place (the url I got is https://127.0.0.1/users/login), but got a 404 response.(Not Found The requested URL was not found on this server.)
So the issue is not solved yet. 

Sorry for the confusion.

**Comment by amuehlem** [comment]
you must set the baseurl='https://example.com', or baseurl='https://192.168.1.23'. Something that is reachable from your webbrowser. 127.0.0.1 would be the localhost of your desktop client and not the misp server.

**Comment by w5334221234555** [comment]
Update:

Finally it works! I can reach MISP from browser with url https://127.0.0.1 now.

I still left the baseurl as '' but edit the default value of AllowOverride from None to All in /etc/httpd/conf/httpd.conf

```
<Directory "/var/www/MISP/app/webroot">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```

Thank you for your help.
