### ISSUE TITLE
New optional PHP dependency: simdjson

### ISSUE THREAD

**Issue by JoeP-oss** [amuehlem/MISP-RPM#75]
Hi,

Just letting you know MISP have added a new optional dependency to the diagnostics page:

`simdjson` available in `php74-php-pecl-simdjson` - diag page says this is to decode JSON structures faster.

Could this be added as a dependency to the RPM?

**Comment by amuehlem** [comment]
Hi JoeP-oss

Thank you for the hint, I've added it as a dependency for the next version.

Best
Andreas
