### ISSUE TITLE
RHEL 8.6 - RPM  - can't install misp_modules

### ISSUE THREAD

**Issue by dvz-rs** [amuehlem/MISP-RPM#76]
This is similar to #39 but for RHEL 8

`dnf install --nobest misp-modules
Updating Subscription Management repositories.
EPEL8 x86_64                                                                                                    41 kB/s | 2.8 kB     00:00
FAI Client for RHEL8                                                                                            35 kB/s | 2.1 kB     00:00
OSB Client for x86_64                                                                                           29 kB/s | 2.1 kB     00:00
Red Hat CodeReady Linux Builder for RHEL 8 x86_64 (RPMs)                                                        49 kB/s | 2.8 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                                           32 kB/s | 2.4 kB     00:00
Red Hat Satellite Tools 6.7 for RHEL 8 x86_64 (RPMs)                                                            35 kB/s | 2.1 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                                        32 kB/s | 2.8 kB     00:00
Error:
 Problem: conflicting requests
  - package misp-modules-2.4.154-1.el8.x86_64 requires glibc(x86-32), but none of the providers can be installed
  - package misp-modules-2.4.154-2.el8.x86_64 requires glibc(x86-32), but none of the providers can be installed
  - package misp-modules-2.4.154-4.el8.x86_64 requires glibc(x86-32), but none of the providers can be installed
  - package misp-modules-2.4.159-1.el8.x86_64 requires glibc(x86-32), but none of the providers can be installed
  - package misp-modules-2.4.160-1.el8.x86_64 requires glibc(x86-32), but none of the providers can be installed
  - package misp-modules-2.4.163-1.el8.x86_64 requires glibc(x86-32), but none of the providers can be installed
  - glibc-2.28-101.el8.i686 has inferior architecture
  - glibc-2.28-72.el8.i686 has inferior architecture
  - glibc-2.28-72.el8_1.1.i686 has inferior architecture
  - glibc-2.28-127.el8.i686 has inferior architecture
  - glibc-2.28-42.el8.i686 has inferior architecture
  - glibc-2.28-42.el8_0.1.i686 has inferior architecture
  - glibc-2.28-127.el8_3.2.i686 has inferior architecture
  - glibc-2.28-151.el8.i686 has inferior architecture
  - glibc-2.28-164.el8.i686 has inferior architecture
  - cannot install both glibc-2.28-101.el8.x86_64 and glibc-2.28-189.5.el8_6.x86_64
  - cannot install both glibc-2.28-72.el8.x86_64 and glibc-2.28-189.5.el8_6.x86_64
  - cannot install both glibc-2.28-72.el8_1.1.x86_64 and glibc-2.28-189.5.el8_6.x86_64
  - cannot install both glibc-2.28-127.el8.x86_64 and glibc-2.28-189.5.el8_6.x86_64
  - cannot install both glibc-2.28-42.el8.x86_64 and glibc-2.28-189.5.el8_6.x86_64
  - cannot install both glibc-2.28-42.el8_0.1.x86_64 and glibc-2.28-189.5.el8_6.x86_64
  - cannot install both glibc-2.28-127.el8_3.2.x86_64 and glibc-2.28-189.5.el8_6.x86_64
  - cannot install both glibc-2.28-151.el8.x86_64 and glibc-2.28-189.5.el8_6.x86_64
  - cannot install both glibc-2.28-164.el8.x86_64 and glibc-2.28-189.5.el8_6.x86_64
  - package glibc-gconv-extra-2.28-189.5.el8_6.x86_64 requires glibc(x86-64) = 2.28-189.5.el8_6, but none of the providers can be installed
  - problem with installed package glibc-gconv-extra-2.28-189.5.el8_6.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)`

**Comment by amuehlem** [comment]
Hi dvz-rs

Is something blocking the installation of 32bit i686 packages on your system? The misp-modules needs the glibc libararies in 32 bit version (i686) for some dependencies of python modules.

Cheers
Andreas

**Comment by amuehlem** [comment]
no update since Nov 2022
