### ISSUE TITLE
MISP doesn't recognize the new MariaDB data location

### ISSUE THREAD

**Issue by iZAK328** [amuehlem/MISP-RPM#78]
- Host: RHEL 8.7
- MISP version: 2.4.165 (RPM)

Hi, 

I had recently found that the MariaDB data location ( **/var/lib/mysql** ) has been filling up and I had tried changing the location to another mount with higher storage capacity as shown in the documentation [MariaDB data location change](https://www.digitalocean.com/community/tutorials/how-to-change-a-mariadb-data-directory-to-a-new-location-on-centos-7). 

However, when starting the mariadb service, it seems to be running fine although MISP doesn't seem to point to the new location to fetch the data and the UI ends up with the following error
![image](https://user-images.githubusercontent.com/33455711/209603813-5595409a-c23d-420d-90fc-fe7d4d5b1b43.png)

Logs 
`2022-12-27 03:16:11 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#2 /var/www/MISP/app/Controller/AppController.php(803): ConnectionManager::getDataSource()
#3 /var/www/MISP/app/Controller/AppController.php(133): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Controller/EventsController.php(68): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): EventsController->beforeFilter()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#10 {main}`

The goal here is to move the database location to another mount since /var/lib/mysql has been filling up. 

Thanks

**Comment by amuehlem** [comment]
Hello iZAK328

Are you sure your MariaDB instance is running without any issues and all the tables from MISP are available? MISP only knows the db connection from the database.php file in the config directory. If you can connect with the credentials stored in this file and you see all the tables, everything should run.

From the logs it seems the connection to the database cannot be established.

**Comment by amuehlem** [comment]
no updated since Dec 2022
