### ISSUE TITLE
Plans to have RPMs for RHEL 9.x?

### ISSUE THREAD

**Issue by CysihZ** [amuehlem/MISP-RPM#79]
Are there any plans (and if so can you give some kind of schedule) to provide your RPMs for RHEL 9.x too?

Thank you very much for the work you put into this project!

**Comment by amuehlem** [comment]
Hello CysihZ

Yes, the task is planned. I had to upgrade my build environment first, but should be able to start working on RHEL9 RPMs in the next weeks. I hope to have them ready beginning on May.

Best

**Comment by CysihZ** [comment]
Great news!
Thank you very much for the heads up and best regards!

**Comment by amuehlem** [comment]
Hi CysihZ

I was cought up with other tasks, but finally found the time to work on the RHEL9 packages. I'm still testing, but if you wannt to have a look https://github.com/amuehlem/MISP-RPM/blob/master/RHEL9.md

Best
