### ISSUE TITLE
Unable to login to MISP 2.4.176

### ISSUE THREAD

**Issue by iZAK328** [amuehlem/MISP-RPM#86]
Hi, 

We're now unable to log into MISP version 2.4.176 and get the following error. 

|OS| MISP version|
|----|----|
|RHEL 8.8|2.4.176|

>Error

`2023-10-09 09:25:47 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.totp' in 'field list'
Request URL: /users/login?_=1696843538181
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Model/AppModel.php(4008): Model->find()
#7 /var/www/MISP/app/Controller/UsersController.php(1205): AppModel->find()
#8 [internal function]: UsersController->login()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#13 {main}
`

Please help resolve this issue. 

Alternatively is there a way to obtain an older rpm preferably version 2.4.165 ?

Thanks,

**Comment by amuehlem** [comment]
Hi

Looks your DB is missing some columns
```
Column not found: 1054 Unknown column 'User.totp' 
```

I've re-added version 2.4.165 to the repository
https://certrepo.switch.ch/certrepo/misp8/misp-2.4.165-1.el8.x86_64.rpm
https://certrepo.switch.ch/certrepo/misp8/misp-python-virtualenv-2.4.165-1.el8.x86_64.rpm

**Comment by iZAK328** [comment]
Hi thanks for the re-adding the older version. Would you be able to hold it in the repo for 2 days since that could give us some time to set it back up. 

Also is the error due to a database schema change in the later versions from 165 ?

**Comment by amuehlem** [comment]
I'll keep the older version for a longer time, no hurry.

Regarding the DB schema, you'll have to ask the [MISP project](https://github.com/MISP/MISP), I don't know what they change between the releases.
Under Administration -> Server Settings & Maintenance -> Diagnostics you should see if the DB schema is correct or not. If not you'll have to ask the MISP people for help, I'm only packaging the software.

**Comment by iZAK328** [comment]
Hi Andres, 

I found the package in the repo but I wasn't able to get the following packages as they don't seem to be part of the repo. 

![image](https://github.com/amuehlem/MISP-RPM/assets/33455711/ab5bc325-ab77-4412-9f14-e66041ed9c5e)

Please let me know how I can obtained these packages. 

Thank you for your patience and assistance.

**Comment by iZAK328** [comment]
Yes I got it activated and working. 

Thank you so much for your time and patience. Please close the ticket.
