### ISSUE TITLE
error 404 not found mariadb resource downloading from repository

### ISSUE THREAD

**Issue by romarito90** [amuehlem/MISP-RPM#89]
Hello @amuehlem 

I tried to install MISP today and I found the following error 404 not found with one resource from the MariaDB repository 

I think this resource is missing or erasing from the page 

I can't continue with the next steps because of it

When I run the next command I got the error

dnf install misp misp-python-virtualenv

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/cab4c86b-2da0-4fdf-a2ad-201b0622c1d6)

This is the problem

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/52b29b0a-5f1b-4e31-b318-385e20d5c5c6)

I go to the resource in the page and it is not found 

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/e956fffc-19f6-4bfe-886b-129a8b67fc45)

Please if you can fix it or what I need to do to keep installing MISP or how to fix this problem 

greetings 

best regards 

Romario

**Comment by amuehlem** [comment]
Hi Romario

Can you check the content of /etc/yum.repos.d/misp.repo?
The MariaDB Repo URL should be https://yum.mariadb.org/10.5/centos8-amd64, in your case it's 10.8 which doesn't exist.

If you want to user a newer version of MariaDB you could also use https://yum.mariadb.org/10.11.6/rhel8-amd64.

Best
Andreas

**Comment by romarito90** [comment]
Thank you so much @amuehlem 

yes, I change the version from 10.8 to 10.11.6 and it works 

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/ab69731c-242d-47ef-b992-9329f0032dc4)

best regards 

Romario
