### ISSUE TITLE
python-pymisp and python34-pymisp contain files owned by other packages

### ISSUE THREAD

**Issue by Brueggus** [amuehlem/MISP-RPM#9]
After recent changes, python-pymisp-2.4.90-2.el7.noarch.rpm and python34-pymisp-2.4.90-2.el7.noarch.rpm contain lots of files owned by other packages. Therefore it's impossible to install them on a default CentOS 7.

See `rpm -qlp python34-pymisp-2.4.90-2.el7.noarch.rpm | less` for example.

To reproduce: run `yum install python-pymisp python34-pymisp` on a default CentOS 7 installation.

**Comment by amuehlem** [comment]
I've changed the SPECs to use the previous installation method, only installing pymisp for python 2 and 3, the other packages are separated. Now you should be able to install them on CentOS7.

**Comment by Brueggus** [comment]
Thanks a lot, the updated packages install fine!
