### ISSUE TITLE
mariadb-secure-installation command not found and error mariadb versions

### ISSUE THREAD

**Issue by romarito90** [amuehlem/MISP-RPM#90]
Hello @amuehlem 

I have the following problem when I tried to run the commnad 

mariadb-secure-installation

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/3023d70a-f3f8-4be6-b9df-274827ec709a)

Why?? MariaDB is installed and active

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/54e88b8f-57ed-4536-9cf1-0f748b6927fb)

I note the following weird thing 

When I change the version of mariaDB version in misp repo it doesnt take the version that I choose like 10.5 in this case 

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/9dc12951-39be-43d1-9a1b-e3786bce6ec1)

MariaDB is taken from another repository and installed the version 10.3

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/4f34f99a-657a-4e13-9713-b844a6b0bde1)

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/410e7dba-8717-4114-986e-ed28a54b805a)

The version 3:10.3.39-1.module+el8.8.0+19673+72b0d35f
repository  rhel-8-for-x86_64-appstream-rpms

and when I check if MariaDB-server is installed I have errors 

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/1eeaf706-f3d6-4de6-b0b4-f64f53943e39)

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/6fb70c57-b6d6-417f-9628-d2de6d26c931)

Maybe this because the installation of the version 10.3 first and then try to install 10.5 version but why ?

If you can help me please to fix this and how to run the command mariadb-secure-installation

**Comment by amuehlem** [comment]
Maybe the command is written with underlines instead of hyphens. ```mysql_secure_installation```

The Version 10.3 seems to come from one of the official RHEL repositories. If you want, you can use this version. If you want to use a newer version, you can try to install it by disabling the official repository
```yum --disablerepo= rhel-8-for-x86_64-appstream-rpms --enablerepo=mariadb install MariaDB-server MariaDB-client MariaDB-compat MariaDB-common```

**Comment by romarito90** [comment]
Thank you so much @amuehlem 

I'm going to use the version 10.3 

and I used the command   mysql_secure_installation

![image](https://github.com/amuehlem/MISP-RPM/assets/114606380/5dee2cda-7dea-46b6-b447-9a2d345f528f)

It works 

best regards 

Romario
