### ISSUE TITLE
Upgrade to 2.4.185

### ISSUE THREAD

**Issue by karnamonkster** [amuehlem/MISP-RPM#91]
Hi,
Do we have the upgrade available for RHEL 8 for the latest version ? 
Been struggling at 2.4.184 cause of the Feed synchronisation issues.

Is there a way to upgrade the RPM install using the source (not that I want to). But any help would be highly appreciated.

Regards

**Comment by amuehlem** [comment]
Hi

I've created the RPMs and uploaded them to the repository. Please check it out!

Best
Andreas

**Comment by karnamonkster** [comment]
Thanks a lot!
