### ISSUE TITLE
Installing MISP without the MariaDB dependency

### ISSUE THREAD

**Issue by highpingblorg** [amuehlem/MISP-RPM#93]
Current MISP RPM installation requires local MariaDB, limiting use cases with remote MySQL databases.

Proposal: Make MariaDB dependency optional for more deployment flexibility. 

Benefits:

- Increased deployment flexibility
- Reduced resource consumption
- Improved manageability

**Comment by amuehlem** [comment]
Hi

Thank you for this proposition. I'll check what I can separate from the installation, some MariaDB libraries might still necessary on the MISP server, but the DB could definitively be installed on a different host.

**Comment by amuehlem** [comment]
Hi

I've checked and tested the setup and the next release 2.4.193 will not have the dependency built into the RPM. I'll adjust the Install docs accordingly.
