### ISSUE TITLE
MISP package 2.4.191-1.e18.x86_64 issue

### ISSUE THREAD

**Issue by Gh1Dra0** [amuehlem/MISP-RPM#94]
When updating using the certrepo.switch.ch to misp v2.4.191 after installing package 2.4.191-1.e18.x86_64 for rhel8 it is updating misp to n-1 version v2.4.190.

Can you check if this is expected?

**Comment by amuehlem** [comment]
Hi

2.4.191 was a quick fix release to solve a bug introduced in 2.4.190. It seems the developers forgot to update the version file in this quick release.
I'm currently compiling the new version 2.4.192 and will check if the shown version in MISP corresponds with the RPM version of the RPM.
