### ISSUE TITLE
Parsing primary.xml error: Start tag expected, '<' not found

### ISSUE THREAD

**Issue by luisabauer** [amuehlem/MISP-RPM#95]
Hi,
We are receiving the message error when we are running: yum update 

For knowledge:
I ran: 
mv misp.repo bkp
yum install http://repo.misp-project.ch/yum/misp/misp-release-latest.el7.noarch.rpm
then 
yum update

then, 
received the message error:
[root@xxxxxxx yum.repos.d]# yum install misp
Loaded plugins: langpacks, susemanagerplugin, venv-yumnotify, versionlock
misp                                                                                              | 1.5 kB  00:00:00

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
...
Parsing primary.xml error: Start tag expected, '<' not found
.

the misp.repo:
# MISP repositories
[misp]
name=misp
baseurl=https://repo.misp-project.ch/yum/misp
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-KOJI-SWITCH
        file:///etc/pki/rpm-gpg/RPM-GPG-KEY-KOJI-MISPPROJECT
gpgcheck=1

but,
running : curl -k "https://repo.misp-project.ch/yum/misp"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
html>head>
title>301 Moved Permanently</title>
</head>body>
h1>Moved Permanently</h1>
p>The document has moved <a href="https://repo.misp-project.ch/yum/misp/">here</a>.</p>
/body></html>

This page show a misp.repo
[misp]
name=misp
baseurl=https://certrepo.switch.ch/certrepo/misp
enabled=1

this do not work too

**Comment by amuehlem** [comment]
can you try to clear all caches?

```
yum clean all
```

And then try to install MISP

```
yum install misp
```

You should see yum updating the repository information from https://repo.misp-project.ch/

**Comment by luisabauer** [comment]
![Captura de tela 2024-07-09 161253](https://github.com/amuehlem/MISP-RPM/assets/64374386/9562673a-87cc-4729-ab09-4562da5787de)

well , same problem yet

**Comment by amuehlem** [comment]
Could be EL7 needs GZ compression, my new webserver started to compress the repo files with zstd. Can you re-try?

```
yum clean all
yum install misp
```
 
This should try to download the updated repository.

**Comment by amuehlem** [comment]
by the way, EL7 is end of life. I will not be able to provide any newer misp packages.

**Comment by luisabauer** [comment]
![Captura de tela 2024-07-09 165219](https://github.com/amuehlem/MISP-RPM/assets/64374386/5f0dc06c-a246-4633-9731-32508a90c034)

Greate !!
Now it´s worked
