### ISSUE TITLE
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### ISSUE THREAD

**Issue by LintStalker** [amuehlem/MISP-RPM#98]
I was able to get through all of the instructions, but when I try to browse out to the site, this message is displayed:

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

Keyboard shortcuts for this page:
L: Go to event list
E: Go to add event page
?: Show this help
Could not locate the PGP public key.

There's no mention in the instructions about creating a PGP public key

**Comment by amuehlem** [comment]
Can you check the logfiles in ```/var/www/MISP/app/tmp/logs/error.log``` and ```/var/log/audit.log```? I'm currently debugging a similar error, caused by SELINUX preventing the php-fpm process to connect to mariadb.

**Comment by amuehlem** [comment]
There was a problem with SELinux and php-fpm. I've updated the RHEL9 package to 2.4.196-2 which includes a new SELinux policy to enable the php74-php-fpm to connect to mariadb.

**Comment by LintStalker** [comment]
Awesome!  I will give it a shot and report back what happens.  Thank You!

**Comment by LintStalker** [comment]
I tried going through the instructions from the Upgrade section and when running this step:

rpm -e --nodeps MariaDB-server  

I get this message:  
error: package MariaDB-server is not installed

**Comment by amuehlem** [comment]
can you run the following command? It will show which mariadb packets are installed on the system

```
rpm -qa|grep -i mariadb
```

**Comment by amuehlem** [comment]
The upgrade section is just for upgrading a fully working MISP instance. The steps for MariaDB are just needed when you want to upgrade to a newer version of MariaDB. As RHEL is offering a 10 year upgrade cycle, there might be new versions of MariaDB available which you might want to upgrade to.

**Comment by amuehlem** [comment]
> I'm running RHEL 9. Which step do I need to redo to get the update?

```dnf upgrade misp misp-python-virtualenv```

**Comment by LintStalker** [comment]
> rpm -qa|grep -i mariadb

When I run that, these are the results:


mariadb-connector-c-config-3.2.6-1.el9_0.noarch
mariadb-connector-c-3.2.6-1.el9_0.x86_64
mariadb-common-10.5.22-1.el9_2.x86_64
mariadb-errmsg-10.5.22-1.el9_2.x86_64
perl-DBD-MariaDB-1.21-16.el9_0.x86_64
mariadb-10.5.22-1.el9_2.x86_64
mariadb-backup-10.5.22-1.el9_2.x86_64
mariadb-gssapi-server-10.5.22-1.el9_2.x86_64
mariadb-server-10.5.22-1.el9_2.x86_64
mariadb-server-utils-10.5.22-1.el9_2.x86_64

**Comment by amuehlem** [comment]
Ah I see you've installed the mariadb-server from the official repository and not from the MariaDB repository. In this case upper and lowercase take effect. But you should think if you want to upgrade MariaDB in your case or not. When you're fine with the mariadb version provided in the official distribution repository, you don't need to upgrade it. If you want to use a newer version from the official MariaDB repository, then you might want to upgrade it.

**Comment by amuehlem** [comment]
Have you configured database access in MISP/app/Config/database.php and is MariaDB running?

**Comment by LintStalker** [comment]
>  MariaDB running?
 
Hmmmm... apparently not:

 systemctl status mariadb.service
× mariadb.service - MariaDB 11.4.3 database server
     Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/mariadb.service.d
             └─migrated-from-my.cnf-settings.conf
     Active: failed (Result: exit-code) since Wed 2024-09-18 09:32:37 EDT; 1 day 22h ago
       Docs: man:mariadbd(8)
             https://mariadb.com/kb/en/library/systemd/
    Process: 1138 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=216/GROUP)
        CPU: 1ms

Sep 18 09:32:37 mispcyber systemd[1]: Starting MariaDB 11.4.3 database server...
Sep 18 09:32:37 mispcyber systemd[1]: mariadb.service: Control process exited, code=exited, status=216/GROUP
Sep 18 09:32:37 mispcyber systemd[1]: mariadb.service: Failed with result 'exit-code'.
Sep 18 09:32:37 mispcyber systemd[1]: Failed to start MariaDB 11.4.3 database server.

**Comment by LintStalker** [comment]
> Have you configured database access in MISP/app/Config/database.php and is MariaDB running?

It seems to be working now!  I had mis configured the database.php file.   

I still see the message at the bottom that say's that Could not locate the PGP public key, but I am getting a login screen

**Comment by amuehlem** [comment]
When you see the login screen and can login using the default credentials, the installation was successful.

The GPG Key can be added in the settings section, see the official MISP documentation https://www.circl.lu/doc/misp/ for more details.

**Comment by LintStalker** [comment]
Thanks!  It seems to be working now
