### ISSUE TITLE
Parsing primary.xml error: Start tag expected, '<' not found (again)

### ISSUE THREAD

**Issue by mcschlup** [amuehlem/MISP-RPM#99]
I know RHEL7 is EOL now ... but as long as you still provide new packages for it: Would it be possible to (re-)create the RHEL7-based repo with the "--general-compress-type=gz" option to createrepo?
see also #95 
Thanks

**Comment by amuehlem** [comment]
Ooops, I thought I had fixed this in my scripts, but I didn't :-(
I recreated the EL7 repository and adjusted my scripts to do this by default for EL7.

Best
Andreas

**Comment by mcschlup** [comment]
Thanks a lot! Works as expected now ...
